### ISSUE TITLE
Grab bag of regression issues after Preact refactoring

### ISSUE THREAD

**Issue by bbbco** [zalando-incubator/bro-q#294]
The Preact implementation does not quite match up with the 1.4 version of bro/q. 

Some regression items I noticed in no particular order:
- Missing logo on right hand side
- Missing "Copy Sharable URL" button
- No margin around (?) button and Copy buttons below the input/output
- The ACE editor window should not stretch below the bottom of the window to require scrolling the page to see long content (the input/output editors should be scrollable themselves)
- As https://github.com/zalando-incubator/bro-q/issues/224 indicates, the liveURLQuery option does not work
- No button option to hide unfiltered input view
- Needs a version bump to 1.5?

**Comment by mrandi** [comment]
I observe this one too:
The ACE editor window should not stretch below the bottom of the window to require scrolling the page to see long content (the input/output editors should be scrollable themselves)

I started working on this, but I don't have enough time currently, that's why I created only a pre release of your last contribution.

**Comment by mrandi** [comment]
@artdaw do you maybe have a bit of time to check this points?

**Comment by bbbco** [comment]
I have a few of these items already fixed. I can put a PR in for them.

**Comment by mrandi** [comment]
@bbbco thx!
